// <auto-generated />
using System;
using IT_department_Assienment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT_department_Assienment.Migrations
{
    [DbContext(typeof(ITdepartmentContext))]
    partial class ITdepartmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT_department_Assienment.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCategoryID");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcquisitionDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceCategoryID = 2,
                            Memo = "Office Desktop",
                            Name = "HP Desktop 1190"
                        },
                        new
                        {
                            Id = 2,
                            AcquisitionDate = new DateTime(2018, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceCategoryID = 1,
                            Memo = "Color Printer",
                            Name = "Canon Printer 3000"
                        },
                        new
                        {
                            Id = 3,
                            AcquisitionDate = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceCategoryID = 3,
                            Memo = "Network Switch",
                            Name = "Cisco Switch 2960"
                        });
                });

            modelBuilder.Entity("IT_department_Assienment.Models.DeviceCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Printer"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Switch"
                        });
                });

            modelBuilder.Entity("IT_department_Assienment.Models.DevicePropertyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int>("PropertyItemID")
                        .HasColumnType("int");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceID");

                    b.HasIndex("PropertyItemID");

                    b.ToTable("DevicePropertyValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceID = 1,
                            PropertyItemID = 4,
                            PropertyValue = "Core i7"
                        },
                        new
                        {
                            Id = 2,
                            DeviceID = 1,
                            PropertyItemID = 1,
                            PropertyValue = "192.168.1.5"
                        },
                        new
                        {
                            Id = 3,
                            DeviceID = 2,
                            PropertyItemID = 1,
                            PropertyValue = "192.168.1.10"
                        },
                        new
                        {
                            Id = 4,
                            DeviceID = 2,
                            PropertyItemID = 2,
                            PropertyValue = "Yes"
                        },
                        new
                        {
                            Id = 5,
                            DeviceID = 3,
                            PropertyItemID = 9,
                            PropertyValue = "24"
                        },
                        new
                        {
                            Id = 6,
                            DeviceID = 3,
                            PropertyItemID = 10,
                            PropertyValue = "1G"
                        });
                });

            modelBuilder.Entity("IT_department_Assienment.Models.PropertyItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceCategoryID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCategoryID");

                    b.ToTable("PropertyItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IP",
                            DeviceCategoryID = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Is Color",
                            DeviceCategoryID = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Brand",
                            DeviceCategoryID = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Processor",
                            DeviceCategoryID = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "HD",
                            DeviceCategoryID = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "RAM",
                            DeviceCategoryID = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Display",
                            DeviceCategoryID = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Current User",
                            DeviceCategoryID = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ports",
                            DeviceCategoryID = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Speed",
                            DeviceCategoryID = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "Brand",
                            DeviceCategoryID = 3
                        });
                });

            modelBuilder.Entity("IT_department_Assienment.Models.Device", b =>
                {
                    b.HasOne("IT_department_Assienment.Models.DeviceCategories", "DeviceCategory")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceCategory");
                });

            modelBuilder.Entity("IT_department_Assienment.Models.DevicePropertyValue", b =>
                {
                    b.HasOne("IT_department_Assienment.Models.Device", "Device")
                        .WithMany("DevicePropertyValues")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IT_department_Assienment.Models.PropertyItems", "PropertyItems")
                        .WithMany("DevicePropertyValues")
                        .HasForeignKey("PropertyItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("PropertyItems");
                });

            modelBuilder.Entity("IT_department_Assienment.Models.PropertyItems", b =>
                {
                    b.HasOne("IT_department_Assienment.Models.DeviceCategories", "DeviceCategory")
                        .WithMany("PropertyItems")
                        .HasForeignKey("DeviceCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceCategory");
                });

            modelBuilder.Entity("IT_department_Assienment.Models.Device", b =>
                {
                    b.Navigation("DevicePropertyValues");
                });

            modelBuilder.Entity("IT_department_Assienment.Models.DeviceCategories", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("PropertyItems");
                });

            modelBuilder.Entity("IT_department_Assienment.Models.PropertyItems", b =>
                {
                    b.Navigation("DevicePropertyValues");
                });
#pragma warning restore 612, 618
        }
    }
}
